version: '3.9'

services:
  db:
    image: mysql:lts
    container_name: mysql_practique
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: practique
    ports:
      - '3306:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql
